# Generated by Django 6.0.3 on 2026-04-13 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("comercial", "0004_merge_0003_ambiente_detalhes_0002_comercial_groups"),
        ("pcp", "0006_alter_processamentopcp_data_liberacao_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_pedido",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Número do Pedido",
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        verbose_name="ID Cliente (Dinabox)",
                    ),
                ),
                (
                    "cliente_nome",
                    models.CharField(max_length=255, verbose_name="Nome do Cliente"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONTRATO_FECHADO", "Contrato Fechado"),
                            ("EM_ENGENHARIA", "Em Engenharia"),
                            ("EM_PRODUCAO", "Em Produção"),
                            ("EXPEDICAO", "Expedição"),
                            ("MONTAGEM", "Montagem"),
                            ("CONCLUIDO", "Concluído"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        db_index=True,
                        default="CONTRATO_FECHADO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_contrato",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Contrato"
                    ),
                ),
                (
                    "data_entrega_prevista",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Entrega Prevista"
                    ),
                ),
                (
                    "data_conclusao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Conclusão"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "cliente_comercial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos",
                        to="comercial.clientecomercial",
                        verbose_name="Cliente Comercial",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoStatusPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_anterior",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Status Anterior"
                    ),
                ),
                (
                    "status_novo",
                    models.CharField(max_length=20, verbose_name="Status Novo"),
                ),
                (
                    "motivo",
                    models.TextField(blank=True, verbose_name="Motivo da Transição"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Transição"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historicos_pedido_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_status",
                        to="pedidos.pedido",
                        verbose_name="Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Status do Pedido",
                "verbose_name_plural": "Históricos de Status do Pedido",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="AmbientePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_ambiente",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Nome do Ambiente"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "acabamentos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ex: ['Laminado Cinza', 'Vidro Temperado']",
                        verbose_name="Acabamentos",
                    ),
                ),
                (
                    "eletrodomesticos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ex: ['Fogão Consul', 'Geladeira Brastemp']",
                        verbose_name="Eletrodomésticos",
                    ),
                ),
                (
                    "observacoes_especiais",
                    models.TextField(
                        blank=True,
                        help_text="Ex: 'Bicama na suite ana'",
                        verbose_name="Observações Especiais",
                    ),
                ),
                (
                    "dados_engenharia",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extrahdos da API Dinabox",
                        verbose_name="Dados de Engenharia",
                    ),
                ),
                (
                    "metricas_pcp_resumo",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Agregados dos lotes vinculados",
                        verbose_name="Métricas PCP (Resumo)",
                    ),
                ),
                (
                    "dados_operacionais_resumo",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Agregados de bipagem, expedição, etc",
                        verbose_name="Dados Operacionais (Resumo)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("EM_ENGENHARIA", "Em Engenharia"),
                            ("AGUARDANDO_PCP", "Aguardando PCP"),
                            ("EM_INDUSTRIA", "Em Indústria"),
                            ("EM_MONTAGEM", "Em Montagem"),
                            ("CONCLUIDO", "Concluído"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "lotes_pcp",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ambientes_pedido",
                        to="pcp.lotepcp",
                        verbose_name="Lotes PCP",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ambientes",
                        to="pedidos.pedido",
                        verbose_name="Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ambiente do Pedido",
                "verbose_name_plural": "Ambientes do Pedido",
                "ordering": ["pedido", "nome_ambiente"],
            },
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(
                fields=["numero_pedido", "status"], name="pedido_num_st_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(
                fields=["customer_id", "status"], name="pedido_cli_st_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(
                fields=["status", "-data_criacao"], name="pedido_st_dt_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historicostatuspedido",
            index=models.Index(
                fields=["pedido", "-data_criacao"], name="hist_ped_dt_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ambientepedido",
            index=models.Index(fields=["pedido", "status"], name="amb_ped_st_idx"),
        ),
        migrations.AddIndex(
            model_name="ambientepedido",
            index=models.Index(
                fields=["status", "-data_atualizacao"], name="amb_st_dt_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ambientepedido",
            unique_together={("pedido", "nome_ambiente")},
        ),
    ]
