# Generated by Django 4.2.29 on 2026-04-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambientepedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("PENDENTE_PROJETOS", "Pendente Projetos"),
                    ("EM_ENGENHARIA", "Em Engenharia"),
                    ("AGUARDANDO_PCP", "Aguardando PCP"),
                    ("EM_INDUSTRIA", "Em Indústria"),
                    ("EM_MONTAGEM", "Em Montagem"),
                    ("CONCLUIDO", "Concluído"),
                ],
                db_index=True,
                default="PENDENTE_PROJETOS",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicostatuspedido",
            name="status_anterior",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Status Anterior"
            ),
        ),
        migrations.AlterField(
            model_name="historicostatuspedido",
            name="status_novo",
            field=models.CharField(max_length=32, verbose_name="Status Novo"),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("CONTRATO_FECHADO", "Contrato Fechado"),
                    ("ENVIADO_PARA_PROJETOS", "Enviado para Projetos"),
                    ("EM_ENGENHARIA", "Em Engenharia"),
                    ("EM_PRODUCAO", "Em Produção"),
                    ("EXPEDICAO", "Expedição"),
                    ("MONTAGEM", "Montagem"),
                    ("CONCLUIDO", "Concluído"),
                    ("CANCELADO", "Cancelado"),
                ],
                db_index=True,
                default="CONTRATO_FECHADO",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
