# Generated by Django 6.0.3 on 2026-03-25 00:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessamentoPCP",
            fields=[
                (
                    "id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("nome_arquivo", models.CharField(max_length=255)),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
                ("total_pecas", models.PositiveIntegerField()),
                ("arquivo_saida", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Processamento PCP",
                "verbose_name_plural": "Processamentos PCP",
                "ordering": ["-data"],
            },
        ),
    ]
