# Generated by Django 6.0.3 on 2026-03-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pcp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processamentopcp",
            name="status",
            field=models.CharField(
                choices=[
                    ("processado", "Processado"),
                    ("erro", "Erro"),
                    ("pendente", "Pendente"),
                ],
                default="processado",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="processamentopcp",
            name="arquivo_saida",
            field=models.FileField(
                blank=True, max_length=500, null=True, upload_to="pcp/outputs/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="processamentopcp",
            name="total_pecas",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name="processamentopcp",
            table="pcp_processamentopcp",
        ),
    ]
