# Generated by Django 6.0.3 on 2026-03-30 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estoque", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movimentacao",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Movimentação",
                "verbose_name_plural": "Movimentações",
            },
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="observacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimentacoes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimentacoes",
                to="estoque.produto",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("entrada", "Entrada"),
                    ("saida", "Saída"),
                    ("ajuste", "Ajuste"),
                    ("transferencia", "Transferência"),
                ],
                max_length=15,
            ),
        ),
    ]
