# Generated by Django 4.2.29 on 2026-04-09 00:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("pcp", "0006_alter_processamentopcp_data_liberacao_and_more"),
        (
            "bipagem",
            "0009_rename_bipagem_eve_peca_id_0d64d9_idx_bipagem_eve_peca_id_3ec78b_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvioExpedicao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_por", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "atualizado_por",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("codigo", models.CharField(db_index=True, max_length=30, unique=True)),
                ("descricao", models.CharField(blank=True, max_length=255)),
                ("transportadora", models.CharField(blank=True, max_length=150)),
                ("placa_veiculo", models.CharField(blank=True, max_length=20)),
                ("motorista", models.CharField(blank=True, max_length=150)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTO", "Aberto"),
                            ("RECEBIDO", "Recebido na Expedicao"),
                            ("LIBERADO", "Liberado"),
                        ],
                        db_index=True,
                        default="ABERTO",
                        max_length=20,
                    ),
                ),
                ("recebido_em", models.DateTimeField(blank=True, null=True)),
                ("liberado_em", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Envio de Expedicao",
                "verbose_name_plural": "Envios de Expedicao",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="EnvioExpedicaoItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_por", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "atualizado_por",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("lote_pid", models.CharField(db_index=True, max_length=8)),
                ("cliente_nome", models.CharField(blank=True, max_length=255)),
                ("ambiente_nome", models.CharField(blank=True, max_length=100)),
                ("modulo_nome", models.CharField(blank=True, max_length=100)),
                ("codigo_modulo", models.CharField(blank=True, max_length=50)),
                (
                    "envio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="bipagem.envioexpedicao",
                    ),
                ),
                (
                    "peca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_envio",
                        to="pcp.pecapcp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Envio",
                "verbose_name_plural": "Itens de Envio",
                "ordering": ["ambiente_nome", "modulo_nome", "codigo_modulo", "id"],
            },
        ),
        migrations.CreateModel(
            name="EventoOperacional",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_por", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "atualizado_por",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("RECEBIMENTO_ITEM", "Recebimento do Item"),
                            ("SEPARACAO_RESERVA", "Separacao para Reserva"),
                            ("CORTE", "Corte"),
                            ("BORDA", "Bordo"),
                            ("SEPARACAO_DESTINOS", "Separacao de Destinos"),
                            ("SAIDA_SETOR", "Saida de Setor"),
                            ("EXPEDICAO", "Expedicao"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "movimento",
                    models.CharField(
                        choices=[
                            ("BIPAGEM", "Bipagem"),
                            ("ENTRADA", "Entrada"),
                            ("SAIDA", "Saida"),
                            ("ESTORNO", "Estorno"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "escopo",
                    models.CharField(
                        choices=[
                            ("PECA_PCP", "Peca PCP"),
                            ("MODULO_PCP", "Modulo PCP"),
                            ("MATERIAL_ESTOQUE", "Material de Estoque"),
                        ],
                        db_index=True,
                        default="PECA_PCP",
                        max_length=20,
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("usuario", models.CharField(default="SISTEMA", max_length=100)),
                ("localizacao", models.CharField(blank=True, max_length=100)),
                ("lote_pid", models.CharField(blank=True, db_index=True, max_length=8)),
                (
                    "codigo_modulo",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("ambiente_nome", models.CharField(blank=True, max_length=100)),
                ("destino", models.CharField(blank=True, max_length=100)),
                ("observacao", models.TextField(blank=True)),
                ("momento", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "envio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_operacionais",
                        to="bipagem.envioexpedicao",
                    ),
                ),
                (
                    "peca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_operacionais",
                        to="pcp.pecapcp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento Operacional",
                "verbose_name_plural": "Eventos Operacionais",
                "ordering": ["-momento"],
                "indexes": [
                    models.Index(
                        fields=["etapa", "movimento", "momento"],
                        name="bipa_evtop_eta_mov_idx",
                    ),
                    models.Index(
                        fields=["lote_pid", "etapa"], name="bipa_evtop_lote_eta_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="envioexpedicaoitem",
            constraint=models.UniqueConstraint(
                fields=("envio", "peca"), name="bipagem_envio_item_unico"
            ),
        ),
    ]
