# Generated by Django 4.2.29 on 2026-04-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bipagem", "0010_envioexpedicao_alter_eventobipagem_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventooperacional",
            name="etapa",
            field=models.CharField(
                choices=[
                    ("RECEBIMENTO_ITEM", "Recebimento do Item"),
                    ("SEPARACAO_RESERVA", "Separacao para Reserva"),
                    ("CORTE", "Corte"),
                    ("BORDA", "Bordo"),
                    ("USINAGEM", "Usinagem"),
                    ("FURACAO", "Furacao"),
                    ("SEPARACAO_DESTINOS", "Separacao de Destinos"),
                    ("DUP", "Duplagem"),
                    ("MCX", "Montagem de Caixa"),
                    ("MPE", "Montagem de Perfis"),
                    ("MAR", "Marcenaria"),
                    ("MEL", "Montagem Eletrica"),
                    ("XMAR", "Marcenaria Especial"),
                    ("XBOR", "Borda Manual"),
                    ("CQL", "Qualidade"),
                    ("EXPEDICAO", "Expedicao"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
