# Generated by Django 4.2.29 on 2026-04-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bipagem", "0011_alter_eventooperacional_etapa"),
    ]

    operations = [
        migrations.AddField(
            model_name="envioexpedicao",
            name="ajudante",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="envioexpedicao",
            name="destino_principal",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="envioexpedicao",
            name="destinos_secundarios",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterModelOptions(
            name="envioexpedicao",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Viagem de Expedicao",
                "verbose_name_plural": "Viagens de Expedicao",
            },
        ),
    ]
