# Generated by Django 4.2.29 on 2026-04-16 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pedidos", "0002_alter_ambientepedido_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_projeto",
                    models.CharField(max_length=255, verbose_name="Nome do Projeto"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO_DEFINICOES", "Aguardando Definicoes"),
                            ("AGUARDANDO_PROJETISTA", "Aguardando Projetista"),
                            ("EM_DESENVOLVIMENTO", "Em Desenvolvimento"),
                            ("EM_CONFERENCIA", "Em Conferencia"),
                            ("AGUARDANDO_APROVACAO", "Aguardando Aprovacao"),
                            ("LIBERADO_PARA_PCP", "Liberado para PCP"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        db_index=True,
                        default="AGUARDANDO_DEFINICOES",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("data_inicio_prevista", models.DateField(blank=True, null=True)),
                ("data_fim_prevista", models.DateField(blank=True, null=True)),
                ("data_inicio_real", models.DateTimeField(blank=True, null=True)),
                ("data_fim_real", models.DateTimeField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "ambiente_pedido",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projeto",
                        to="pedidos.ambientepedido",
                        verbose_name="Ambiente do Pedido",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "distribuidor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos_distribuidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liberador_tecnico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos_para_liberacao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to="pedidos.pedido",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "projetista",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos_designados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="AnexoProjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(upload_to="projetos/anexos/%Y/%m/%d/")),
                (
                    "nome_arquivo",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("tipo_anexo", models.CharField(blank=True, default="", max_length=50)),
                ("descricao", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="projetos.projeto",
                        verbose_name="Projeto",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anexos_projetos_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo de Projeto",
                "verbose_name_plural": "Anexos de Projetos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddIndex(
            model_name="projeto",
            index=models.Index(fields=["status", "-criado_em"], name="proj_status_idx"),
        ),
        migrations.AddIndex(
            model_name="projeto",
            index=models.Index(
                fields=["projetista", "status"], name="proj_proj_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projeto",
            index=models.Index(
                fields=["pedido", "status"], name="proj_pedido_status_idx"
            ),
        ),
    ]
