# Generated by Django 4.2.29 on 2026-04-12 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClienteComercial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="ID cliente Dinabox",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("primeiro_contato", "Primeiro contato"),
                            ("em_orcamento", "Em orçamento"),
                            ("em_negociacao", "Em negociação"),
                            ("contrato_fechado", "Contrato fechado"),
                            ("arquivado", "Arquivado"),
                        ],
                        db_index=True,
                        default="primeiro_contato",
                        max_length=32,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clientes_comerciais_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente comercial",
                "verbose_name_plural": "Clientes comerciais",
                "ordering": ["-atualizado_em"],
            },
        ),
        migrations.CreateModel(
            name="ObservacaoComercial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="observacoes_comerciais",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observacoes",
                        to="comercial.clientecomercial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Observação comercial",
                "verbose_name_plural": "Observações comerciais",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="AmbienteOrcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_ambiente", models.CharField(max_length=200)),
                (
                    "valor_orcado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Valor orçado",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ambientes",
                        to="comercial.clientecomercial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ambiente (orçamento)",
                "verbose_name_plural": "Ambientes (orçamento)",
                "ordering": ["ordem", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="clientecomercial",
            index=models.Index(
                fields=["status", "atualizado_em"], name="comercial_cli_st_upd_idx"
            ),
        ),
    ]
