# Generated by Django 4.2.29 on 2026-04-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comercial", "0002_comercial_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambienteorcamento",
            name="acabamentos",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de acabamentos (materiais, cores, dimensões, etc)",
                verbose_name="Acabamentos",
            ),
        ),
        migrations.AddField(
            model_name="ambienteorcamento",
            name="eletrodomesticos",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de eletrodomésticos (marca, modelo, capacidade)",
                verbose_name="Eletrodomésticos",
            ),
        ),
        migrations.AddField(
            model_name="ambienteorcamento",
            name="observacoes_especiais",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Itens que precisam atenção especial na Engenharia",
                verbose_name="Observações especiais",
            ),
        ),
    ]
