# Generated by Django 4.2.29 on 2026-04-12 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comercial", "0003_ambiente_detalhes"),
        ("comercial", "0002_comercial_groups"),
    ]

    operations = []
