# Generated by Django 4.2.29 on 2026-04-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comercial", "0004_merge_0003_ambiente_detalhes_0002_comercial_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientecomercial",
            name="numero_pedido",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Numero comercial definido antes do handoff para Projetos.",
                max_length=50,
                verbose_name="Numero do Pedido",
            ),
        ),
        migrations.AddIndex(
            model_name="clientecomercial",
            index=models.Index(
                fields=["numero_pedido"], name="comercial_cli_pedido_idx"
            ),
        ),
    ]
